name: Automated tests
on: 
  push:
    paths:
      - 'src/**'
      - '.github/*.yaml'
      - 'package.json'
      - 'package-lock.json'
      - '.eslintrc.json'
      - '.github/workflows/tests.yaml'

jobs:
  ci:
    runs-on: ubuntu-latest
    container: node:16
    
    services:
      mongodb:
        image: mongo
        ports:
        - 27017:27017

    steps:    
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Run linter
        run: npm run lint

      - name: Run tests
        run: npm test
        env:
          NODE_ENV: development
          MONGO_URL: 'mongodb://mongodb:27017/enrichment-map-test?retryWrites=true&w=majority'
          PORT: 3000
